//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOfferPrice
    {
        public int OfferId { get; set; }
        public decimal OfferPrice { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public int Product_Id { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Counter { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
