//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblOfferPrices = new HashSet<tblOfferPrice>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string ModelNo { get; set; }
        public string Category { get; set; }
        public string Condition { get; set; }
        public decimal BuyNowPrice { get; set; }
        public decimal BidPrice { get; set; }
        public int Quantity { get; set; }
        public int AddressID { get; set; }
        public System.DateTime BidEndDateTime { get; set; }
        public string ImagePath { get; set; }
        public string AddressLine1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> AddedByUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOfferPrice> tblOfferPrices { get; set; }
        public virtual User User { get; set; }
    }
}
